#!/bin/sh

TOP_LEVEL=$(git rev-parse --show-toplevel)

DOCKER_TOP_LEVEL=/arena
DOCKER_IMAGE=$1
PYTHON_COMPILER=$2
PYTHON_VERSION=$3
DOCKER_PYTHON_PATH=/opt/python/${PYTHON_COMPILER}/bin/python
DOCKER_DIST=${DOCKER_TOP_LEVEL}/dist

docker run -it --mount src="${TOP_LEVEL}",dst="${DOCKER_TOP_LEVEL}",type=bind ${DOCKER_IMAGE} sh -c "
  export ARENA_MANYLINUX_PYTHON3_INCLUDE_DIR=/opt/python/${PYTHON_COMPILER}/include/python${PYTHON_VERSION}
  ${DOCKER_PYTHON_PATH} -m pip install GitPython setuptools wheel
  ${DOCKER_PYTHON_PATH} -m pip wheel -e ${DOCKER_TOP_LEVEL} --no-deps --no-build-isolation -w ${DOCKER_DIST} -v"
