#!/bin/sh

TOP_LEVEL=$(git rev-parse --show-toplevel)

DOCKER_TOP_LEVEL=/arena
DOCKER_IMAGE=$1
PYTHON_VERSION=$2
DOCKER_PYTHON_PATH=/opt/python/${PYTHON_VERSION}/bin/python
DOCKER_DIST=${DOCKER_TOP_LEVEL}/dist
DOCKER_VENV=${DOCKER_DIST}/${DOCKER_IMAGE}/venv/${PYTHON_VERSION}

docker run -it --mount src="${TOP_LEVEL}",dst="${DOCKER_TOP_LEVEL}",type=bind ${DOCKER_IMAGE} sh -c "
  ${DOCKER_PYTHON_PATH} -m venv ${DOCKER_VENV}
  ${DOCKER_VENV}/bin/pip install cmake GitPython setuptools wheel
  ${DOCKER_VENV}/bin/pip wheel -e ${DOCKER_TOP_LEVEL} --require-virtualenv --no-build-isolation --no-deps -w ${DOCKER_DIST}"
