name: check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build
          key: build
      - run: pip3 install pytest
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-10
      - run: cmake --build build --target check iwyu
