name: Check Pip Install
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%W')"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/build
          key: build-${{ steps.date.outputs.date }}
          restore-keys: |
            build
      - run: pip3 install pytest pytest-timeout numpy
      - run: pip3 install -U setuptools
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: pip3 install . -vvv
      - run: pytest test/base.py --timeout=30
